--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aericio/PCEBookShop
build-by-default: true
branches:
- master
projects:
  PCEBookShop:
    path: ""
    libs:
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.2
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
    lint:
      phpstan: false
...
