name: PiggyBookShop
main: Aericio\PCEBookShop\PCEBookShop
version: 2.0.0
api: 5.0.0
load: POSTWORLD
author: antbag
depend: [PiggyCustomEnchants]
soft-depend: [EconomyAPI, BedrockEconomy]
website: "https://github.com/antbag-pm-pl/PiggyBookShop/"
permissions:
  pcebookshop.command.bookshop:
    default: true
    description: "Allows usage of the /pcebookshop command"
